version: "3.7"
services:
  watchtower:
    container_name: watchtower
    hostname: watchtower
    restart: always
    image: v2tec/watchtower
    labels: 
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup --label-enable
networks:
  traefik:
    name: traefik
    driver: bridge